# Generated by Django 5.1.1 on 2024-09-14 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_escolar", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipe",
            name="anexos",
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="tipo_documento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Plano de Ensino", "Plano de Ensino"),
                    ("Plano de Aula", "Plano de Aula"),
                    ("Lista de frequencia", "Lista de Frequência"),
                    ("Outro", "Outro"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AnexoEquipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="documentos/equipe/")),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            (
                                "Documento de identificação",
                                "Documento de identificação",
                            ),
                            ("Comprovante de residência", "Comprovante de residência"),
                            ("Laudo Médico", "Laudo Médico"),
                            ("Outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="gestao_escolar.equipe",
                    ),
                ),
            ],
        ),
    ]
