# Generated by Django 5.1.1 on 2024-09-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestao_escolar",
            "0002_remove_equipe_anexos_alter_disciplina_tipo_documento_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="funcao",
            field=models.CharField(
                choices=[
                    ("Diretoria", "Diretoria"),
                    ("Secretaria", "Secretaria"),
                    ("Coordenação", "Coordenação"),
                    ("Psicólogo", "Psicólogo"),
                    ("Assistente Social", "Assistente Social"),
                    ("Pedagogo", "Pedagogo"),
                    ("Auxiliar de Serviços Gerais", "Auxiliar de Serviços Gerais"),
                    ("Cozinheiro", "Cozinheiro"),
                    ("Merendeira", "Merendeira"),
                    ("Inspetor", "Inspetor"),
                    ("Vigia", "Vigia"),
                    ("Outro", "Outro"),
                ],
                max_length=255,
            ),
        ),
    ]
