# Generated by Django 5.1.1 on 2024-10-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestao_escolar",
            "0004_remove_disciplina_anexos_disciplina_ano_disciplina_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="atendimento",
            name="codigo_atendimento",
            field=models.CharField(
                blank=True, editable=False, max_length=6, unique=True
            ),
        ),
    ]
