# Generated by Django 5.1.1 on 2024-10-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_escolar", "0005_atendimento_codigo_atendimento"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplina",
            name="serie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Educação Infantil", "Educação Infantil"),
                    ("1º Ano", "1º Ano"),
                    ("2º Ano", "2º Ano"),
                    ("3º Ano", "3º Ano"),
                    ("4º Ano", "4º Ano"),
                    ("5º Ano", "5º Ano"),
                    ("6º Ano", "6º Ano"),
                    ("7º Ano", "7º Ano"),
                    ("8º Ano", "8º Ano"),
                    ("9º Ano", "9º Ano"),
                    ("Ensino Médio - 1º Ano", "Ensino Médio - 1º Ano"),
                    ("Ensino Médio - 2º Ano", "Ensino Médio - 2º Ano"),
                    ("Ensino Médio - 3º Ano", "Ensino Médio - 3º Ano"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="tipo_documento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Plano de Ensino", "Plano de Ensino"),
                    ("Plano de Aula", "Plano de Aula"),
                    ("Lista de frequencia", "Lista de Frequência"),
                    ("Notas", "Notas"),
                    ("Outro", "Outro"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AnexoDisciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="documentos/disciplinas/")),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("Plano de Ensino", "Plano de Ensino"),
                            ("Plano de Aula", "Plano de Aula"),
                            ("Lista de frequencia", "Lista de Frequência"),
                            ("Notas", "Notas"),
                            ("Outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="gestao_escolar.disciplina",
                    ),
                ),
            ],
        ),
    ]
