# Generated by Django 5.1.1 on 2024-10-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_escolar", "0007_remove_turma_professores_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="serie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Educação Infantil", "Educação Infantil"),
                    ("1º Ano", "1º Ano"),
                    ("2º Ano", "2º Ano"),
                    ("3º Ano", "3º Ano"),
                    ("4º Ano", "4º Ano"),
                    ("5º Ano", "5º Ano"),
                    ("6º Ano", "6º Ano"),
                    ("7º Ano", "7º Ano"),
                    ("8º Ano", "8º Ano"),
                    ("9º Ano", "9º Ano"),
                    ("Ensino Médio - 1º Ano", "Ensino Médio - 1º Ano"),
                    ("Ensino Médio - 2º Ano", "Ensino Médio - 2º Ano"),
                    ("Ensino Médio - 3º Ano", "Ensino Médio - 3º Ano"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
