# Generated by Django 5.1.1 on 2024-10-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_escolar", "0008_turma_serie"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="codigo_turma",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
