# Generated by Django 5.1.1 on 2024-10-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_escolar", "0009_turma_codigo_turma"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="professores",
            field=models.ManyToManyField(
                blank=True,
                related_name="turmas_professor",
                to="gestao_escolar.professor",
            ),
        ),
    ]
