# Generated by Django 5.1.1 on 2024-10-05 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_escolar", "0010_turma_professores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professor",
            name="tipo_documento",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="turmas",
        ),
        migrations.AlterField(
            model_name="disciplina",
            name="professor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professores_disciplina",
                to="gestao_escolar.professor",
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="disciplinas",
            field=models.ManyToManyField(
                blank=True, related_name="professores", to="gestao_escolar.disciplina"
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="professores",
            field=models.ManyToManyField(
                blank=True, related_name="turmas", to="gestao_escolar.professor"
            ),
        ),
    ]
