# Generated by Django 5.1.1 on 2024-10-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_escolar", "0011_remove_professor_tipo_documento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="tipo_documento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Documento de identificação", "Documento de identificação"),
                    ("Comprovante de residência", "Comprovante de residência"),
                    ("Laudo Médico", "Laudo Médico"),
                    ("Outro", "Outro"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="turmas",
            field=models.ManyToManyField(
                related_name="professores_turma", to="gestao_escolar.turma"
            ),
        ),
        migrations.AlterField(
            model_name="professor",
            name="disciplinas",
            field=models.ManyToManyField(
                blank=True,
                related_name="professores_disciplina",
                to="gestao_escolar.disciplina",
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="professores",
            field=models.ManyToManyField(
                blank=True,
                related_name="turmas_professor",
                to="gestao_escolar.professor",
            ),
        ),
    ]
