# Generated by Django 5.1.1 on 2024-10-26 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("gestao_escolar", "0013_perfilusuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atendimento",
            name="responsavel_atendimento",
        ),
        migrations.AddField(
            model_name="atendimento",
            name="responsavel_content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="responsavel_object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
