# Generated by Django 5.1.1 on 2024-10-27 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao_escolar", "0014_remove_atendimento_responsavel_atendimento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnexoAtendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="documentos/atendimentos")),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            (
                                "Documento de identificação",
                                "Documento de identificação",
                            ),
                            ("Comprovante de residência", "Comprovante de residência"),
                            ("Laudo Médico", "Laudo Médico"),
                            ("Outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "atendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos_atendimento",
                        to="gestao_escolar.atendimento",
                    ),
                ),
            ],
        ),
    ]
